spring.batch.jdbc.initialize-schema=always
spring.batch.jdbc.table-prefix=public.BATCH_
spring.sql.init.platform=postgres

# Max size for a single file
spring.servlet.multipart.max-file-size=100MB
# Max size for the entire multipart request (files + form data)
spring.servlet.multipart.max-request-size=100MB


#spring.application.name=AML
#server.port=8080
#spring.datasource.url=jdbc:postgresql://localhost:5432/aml_test_db
#spring.datasource.username=postgres
#spring.datasource.password=Tanmay25
#spring.datasource.hikari.maximum-pool-size=20
#spring.jpa.hibernate.ddl-auto=none
#spring.flyway.enabled=false
#spring.jpa.open-in-view=false
#spring.batch.job.enabled=false
#app.security.jwt.secret=${JWT_SECRET}
#cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
#cloudinary.api-key=${CLOUDINARY_API_KEY}
#cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
#spring.mail.host=${MAIL_HOST:}
#spring.mail.port=${MAIL_PORT:}
#spring.mail.username=${MAIL_USERNAME:}
#spring.mail.password=${MAIL_PASSWORD:}
#app.security.jwt.expiration-ms=3600000
#app.security.jwt.refresh-expiration-ms=604800000


spring.application.name=AML
server.port=1001
spring.datasource.url=jdbc:postgresql://localhost:5432/anti-money-laundering
spring.datasource.username=postgres
spring.datasource.password=Temp@123456
spring.datasource.hikari.maximum-pool-size=20
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=false
spring.jpa.open-in-view=false
spring.batch.job.enabled=false
app.security.jwt.secret=gZk0cC4JRyRiVXV9wNldKjT4J6OiJxz6L5tF1NkXJwU=
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=odk1572@gmail.com
spring.mail.password=cjxm gjef adgx fqgp
app.security.jwt.expiration-ms=36000000000
app.security.jwt.refresh-expiration-ms=604800000

